### ISSUE TITLE
Error: Dimensions must be equal, but are 33 and 4

### ISSUE THREAD

**Issue by xymtxwd** [datalogue/keras-attention#1]
Hi, I was trying to compile the attention decoder model:

```
# check to see if it compiles
if __name__ == '__main__':
    from keras.layers import Input, LSTM
    from keras.models import Model
    from keras.layers.wrappers import Bidirectional
    i = Input(shape=(100,104), dtype='float32')
    enc = Bidirectional(LSTM(64, return_sequences=True), merge_mode='concat')(i)
    dec = AttentionDecoder(32, 4)(enc)
    model = Model(inputs=i, outputs=dec)
    model.summary()
```
But it reported the following error:
```
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 33 and 4 for 'AttentionDecoder/MatMul_4' (op: 'MatMul') with input shapes: [?,33], [4,33].
```
Any ideas why that would happen? I would greatly appreciate any helps!

**Comment by zafarali** [comment]
I'm curious to know how you're getting a tensor of size 33? When I run the compilation code I can reproduce the error but I get:

`ValueError: Dimensions must be equal, but are 32 and 4 for 'AttentionDecoder/MatMul_4' (op: 'MatMul') with input shapes: [?,32], [4,32].`

It looks like one of my multiplications is happening in the wrong order. Specifically it looks like it's one of the last few calculations since `[?, 32] * [32, 4]  ==> [?, 4]` which is your expected `output_dim`.

**Comment by zafarali** [comment]
Can you tell me what version of keras and tensorflow you are using?

**Comment by zafarali** [comment]
I was able to trace the issue back to an issue with the Keras installation:

To recreate your issue:
```
➜  keras-attention git:(master) ✗ python3 models/custom_recurrents.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "/Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages/tensorflow/python/framework/common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/Users/zaf/anaconda/envs/py34/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 32 and 4 for 'AttentionDecoder/MatMul_4' (op: 'MatMul') with input shapes: [?,32], [4,32].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "models/custom_recurrents.py", line 316, in <module>
    dec = AttentionDecoder(32, 4)(enc)
  File "/Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages/keras/layers/recurrent.py", line 262, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "/Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages/keras/engine/topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "models/custom_recurrents.py", line 210, in call
    return super(AttentionDecoder, self).call(x)
  File "/Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages/keras/layers/recurrent.py", line 341, in call
    input_length=input_shape[1])
  File "/Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages/keras/backend/tensorflow_backend.py", line 2459, in rnn
    outputs, _ = step_function(inputs[0], initial_states + constants)
  File "models/custom_recurrents.py", line 255, in step
    + self.b_r)
  File "/Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages/keras/backend/tensorflow_backend.py", line 976, in dot
    out = tf.matmul(x, y)
  File "/Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages/tensorflow/python/ops/math_ops.py", line 1801, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1263, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 2338, in create_op
    set_shapes_for_outputs(ret)
  File "/Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 1719, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 1669, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 32 and 4 for 'AttentionDecoder/MatMul_4' (op: 'MatMul') with input shapes: [?,32], [4,32].
➜  keras-attention git:(master) ✗ python3
Python 3.4.3 |Anaconda 2.3.0 (x86_64)| (default, Mar  6 2015, 12:07:41)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'1.1.0'
>>> import keras
Using TensorFlow backend.
>>> keras.__version__
'2.0.5'
>>> exit()
```

So I rolled back to keras 2.0.3 that I used when I was writing this repo in 8a015a6. Now:

```
➜  keras-attention git:(master) ✗ sudo pip3 install -r requirements.txt
Password:
The directory '/Users/zaf/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/zaf/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: numpy in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: babel>=1.3 in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: tensorflow>=1.1.0 in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from -r requirements.txt (line 3))
Collecting keras==2.0.3 (from -r requirements.txt (line 4))
Requirement already satisfied: h5py in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: Faker in /Users/zaf/.local/lib/python3.4/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: pytz>=0a in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from babel>=1.3->-r requirements.txt (line 2))
Requirement already satisfied: wheel>=0.26 in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from tensorflow>=1.1.0->-r requirements.txt (line 3))
Requirement already satisfied: werkzeug>=0.11.10 in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from tensorflow>=1.1.0->-r requirements.txt (line 3))
Requirement already satisfied: protobuf>=3.2.0 in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from tensorflow>=1.1.0->-r requirements.txt (line 3))
Requirement already satisfied: six>=1.10.0 in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from tensorflow>=1.1.0->-r requirements.txt (line 3))
Requirement already satisfied: pyyaml in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from keras==2.0.3->-r requirements.txt (line 4))
Requirement already satisfied: theano in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from keras==2.0.3->-r requirements.txt (line 4))
Requirement already satisfied: python-dateutil>=2.4 in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from Faker->-r requirements.txt (line 6))
Requirement already satisfied: setuptools in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from protobuf>=3.2.0->tensorflow>=1.1.0->-r requirements.txt (line 3))
Requirement already satisfied: scipy>=0.14 in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from theano->keras==2.0.3->-r requirements.txt (line 4))
Requirement already satisfied: packaging>=16.8 in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from setuptools->protobuf>=3.2.0->tensorflow>=1.1.0->-r requirements.txt (line 3))
Requirement already satisfied: appdirs>=1.4.0 in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from setuptools->protobuf>=3.2.0->tensorflow>=1.1.0->-r requirements.txt (line 3))
Requirement already satisfied: pyparsing in /Users/zaf/anaconda/envs/py34/lib/python3.4/site-packages (from packaging>=16.8->setuptools->protobuf>=3.2.0->tensorflow>=1.1.0->-r requirements.txt (line 3))
Installing collected packages: keras
  Found existing installation: Keras 2.0.5
    Uninstalling Keras-2.0.5:
      Successfully uninstalled Keras-2.0.5
Successfully installed keras-2.0.3
```

Now:

```
➜  keras-attention git:(master) ✗ python3 models/custom_recurrents.py
Using TensorFlow backend.
2017-06-16 12:59:19.186458: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-16 12:59:19.186481: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-16 12:59:19.186485: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-16 12:59:19.186489: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-16 12:59:19.186493: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
inputs shape: (?, ?, 128)
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         (None, 100, 104)          0
_________________________________________________________________
bidirectional_1 (Bidirection (None, 100, 128)          86528
_________________________________________________________________
AttentionDecoder (AttentionD (None, 100, 4)            25780
=================================================================
Total params: 112,308
Trainable params: 112,308
Non-trainable params: 0
_________________________________________________________________
```

As expected. Something between version 2.0.3 and 2.0.5 in keras changed in the way `K.dot` is handled. I will open an issue there.

Can you confirm this fixes the issue you were having?

**Comment by zafarali** [comment]
After some more digging, Keras 2.0.4 changed their API for `Recurrent` (changing plurals)

https://github.com/fchollet/keras/releases/tag/2.0.4

a47d313 changes `get_initial_states` to `get_initial_state`
2f71813 restores the `requirements.txt`

 Things should be working now!

**Comment by xymtxwd** [comment]
Hi zafarali, thank you for the quick reply! Sorry 33 was a typo, I wanted to say '32', that was my bad! I've tried your updated version, and it works well this time. I was wondering is the model able to handle the situation where the input length, input dimension, output length, output dimension all differ? For example, my dataset looks like: x==[None,5,41], y==[None,8,57] . Is there a way to fit the model to my data? Thank you in advance!

**Comment by zafarali** [comment]
For different input dimensions/out put dimensions yes: just specify the `output_dim` in the `AttentionDecoder`. With regards to different sequence lengths: theoretically if tensorflow had a dynamic computation graph yes. In practice, I'd pad both the sequences to be equal or change the length of the sequence coming into the `AttentionDecoder` using `Repeat` or something else.

**Comment by xtianhb** [comment]
Same problem, solved it changing input resolution to be multiple of 128, eg 640x512

**Comment by xiaoxin05** [comment]
I have the same problem now,when I run the program。I don't know how to solve the above problems. I hope that those who know can help me. Thank you
question is as follows ：
ValueError: Dimensions must be equal, but are 32 and 46 for 'stage1_loss/sub' (op: 'Sub') with input shapes: [?,32,32,22], [?,46,46,22].
