### ISSUE TITLE
Compile issue - Tensors in list passed to 'values' of 'Pack' Op have types [int32, <NOT CONVERTIBLE TO TENSOR>, int32] that don't all match

### ISSUE THREAD

**Issue by ZmeiGorynych** [datalogue/keras-attention#16]
Hi,

I tried using this in a really simple model: 

```
def simple_model(input_dim, units, output_dim=29):
    input_data = Input(name='the_input', shape=(None, input_dim))
    rnn = GRU(units, return_sequences=True, implementation=2)(input_data)
    decoded = AttentionDecoder(units,output_dim)(rnn)
    y_pred = Activation('softmax', name='softmax')(decoded)
    model = Model(inputs=input_data, outputs=y_pred)
    print(model.summary())
    return model
if __name__=='__main__':
    model_5 = simple_model(input_dim=161,units=200,output_dim=29)
```
and keep getting a strange error, see below. Am using keras 2.0.5, Tensorflow 1.1

Any idea what could be the matter? 
Thanks a lot!

```
C:\Users\egork\Anaconda3\envs\aind-vui\python.exe "C:\Program Files\JetBrains\PyCharm 2017.2.2\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 50765 --file C:/Users/egork/Dropbox/GitHub/aind/AIND-VUI-Capstone/sample_models.py
pydev debugger: process 2560 is connecting

Connected to pydev debugger (build 172.3968.37)
Using TensorFlow backend.
inputs shape: (?, ?, 200)
Traceback (most recent call last):
  File "C:\Users\egork\Anaconda3\envs\aind-vui\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 435, in apply_op
    as_ref=input_arg.is_ref)
  File "C:\Users\egork\Anaconda3\envs\aind-vui\lib\site-packages\tensorflow\python\framework\ops.py", line 737, in internal_convert_n_to_tensor
    preferred_dtype=preferred_dtype))
  File "C:\Users\egork\Anaconda3\envs\aind-vui\lib\site-packages\tensorflow\python\framework\ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\egork\Anaconda3\envs\aind-vui\lib\site-packages\tensorflow\python\framework\constant_op.py", line 121, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\egork\Anaconda3\envs\aind-vui\lib\site-packages\tensorflow\python\framework\constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "C:\Users\egork\Anaconda3\envs\aind-vui\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 364, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.2.2\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2017.2.2\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2017.2.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/egork/Dropbox/GitHub/aind/AIND-VUI-Capstone/sample_models.py", line 238, in <module>
    model_5 = simple_model(input_dim=161,units=200,output_dim=29)
  File "C:/Users/egork/Dropbox/GitHub/aind/AIND-VUI-Capstone/sample_models.py", line 177, in simple_model
    decoded = AttentionDecoder(units,output_dim)(rnn)
  File "C:\Users\egork\Anaconda3\envs\aind-vui\lib\site-packages\keras\layers\recurrent.py", line 262, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "C:\Users\egork\Anaconda3\envs\aind-vui\lib\site-packages\keras\engine\topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "C:/Users/egork/Dropbox/GitHub/aind/AIND-VUI-Capstone\custom_recurrents.py", line 210, in call
    return super(AttentionDecoder, self).call(x)
  File "C:\Users\egork\Anaconda3\envs\aind-vui\lib\site-packages\keras\layers\recurrent.py", line 341, in call
    input_length=input_shape[1])
  File "C:\Users\egork\Anaconda3\envs\aind-vui\lib\site-packages\keras\backend\tensorflow_backend.py", line 2459, in rnn
    outputs, _ = step_function(inputs[0], initial_states + constants)
  File "C:/Users/egork/Dropbox/GitHub/aind/AIND-VUI-Capstone\custom_recurrents.py", line 232, in step
    _stm = K.repeat(stm, self.timesteps)
  File "C:\Users\egork\Anaconda3\envs\aind-vui\lib\site-packages\keras\backend\tensorflow_backend.py", line 1864, in repeat
    pattern = tf.stack([1, n, 1])
  File "C:\Users\egork\Anaconda3\envs\aind-vui\lib\site-packages\tensorflow\python\ops\array_ops.py", line 856, in stack
    return gen_array_ops._pack(values, axis=axis, name=name)
  File "C:\Users\egork\Anaconda3\envs\aind-vui\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1949, in _pack
    result = _op_def_lib.apply_op("Pack", values=values, axis=axis, name=name)
  File "C:\Users\egork\Anaconda3\envs\aind-vui\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 463, in apply_op
    raise TypeError("%s that don't all match." % prefix)
TypeError: Tensors in list passed to 'values' of 'Pack' Op have types [int32, <NOT CONVERTIBLE TO TENSOR>, int32] that don't all match.
```

**Comment by ZmeiGorynych** [comment]
Ah, worked it out: my Input had varying sequence lengths, so the corresponding tensor had the size (None, None, a_constant) and the code here was choking on not knowing dimension 1. Changed the code to pad all sequences to constant length, now seems to work fine (compiled, calibration still running).
I'm so switching to pytorch for my next project :)

**Comment by zafarali** [comment]
Glad it worked out! I am in the process of switching as well. They have a
neat dynamic batching thing you can do to increase efficiency

**Comment by Nitinkmr** [comment]
hi, @ZmeiGorynych,I am also having the same issue but not able to reproduce what you said. I padded all the input sequences to a certain max length, so now every input has the same length. but i still get this error. I would be thankful if you or anyone else could help me out with this. Thanks

**Comment by shuuchen** [comment]
@ZmeiGorynych 
@Nitinkmr 
Hi, I have met a similar problem. 
Could you please share your solutions?

I also padded the sequences. 
In the fit function,
The size of dialogue_X_train is (7, 250),  
the size of dialogue_Y_train(7, 250, 40).
```python
def attention_seq2seq(maxLen, vocab_size):

    dialogue_input = Input(shape=(maxLen,))

    embedding = Embedding(input_dim=vocab_size,
                          output_dim=EMBEDDING_SIZE,
                          embeddings_initializer='glorot_uniform',
                          input_length=maxLen)(dialogue_input)

    encode1 = LSTM(HIDDEN_SIZE, return_sequences=True)(embedding)
    encode2 = LSTM(HIDDEN_SIZE, return_sequences=True)(encode1)

    dialogue_output = AttentionDecoder(HIDDEN_SIZE, vocab_size)(encode2)

    model = Model(inputs=dialogue_input, outputs=dialogue_output)
    plot_model(model, 'attention_seq2seq.png', show_shapes=True)

    return model

model = attention_seq2seq(maxLen, vocab_size)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(dialogue_X_train, dialogue_Y_train, batch_size=256, epochs=20, verbose=2)
```

It gave the following errors
```python
Using TensorFlow backend.
inputs shape: (?, ?, 1000)
Traceback (most recent call last):
  File "/Users/shuchendu/PycharmProjects/test/seq2seq/test/test.py", line 59, in <module>
    model.fit(dialogue_X_train, dialogue_Y_train, batch_size=256, epochs=20, verbose=2)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keras/engine/training.py", line 1634, in fit
    self._make_train_function()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keras/engine/training.py", line 990, in _make_train_function
    loss=self.total_loss)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keras/optimizers.py", line 432, in get_updates
    m_t = (self.beta_1 * m) + (1. - self.beta_1) * g
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 885, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 836, in convert_to_tensor
    as_ref=False)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 926, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 371, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
```

Thanks very much.

**Comment by ZmeiGorynych** [comment]
My implementation is at https://github.com/ZmeiGorynych/AIND-VUI-Capstone.
cnn_deep_bidir_rnn_attention_model() in sample_models.py uses AttentionDecoder, and minimal_attention_notebook.ipynb calls it. 

AttentionDecoder is also a bit of a memory hog, so I had to set tiny batch sizes (but bigger than 1) to get it to run, else was getting strange errors.

It actually didn't give great results in my usecase, but at least the calibration ran without errors, as you can see from the notebook.

Hope that helps.

**Comment by LeZhengThu** [comment]
@zafarali 
I used bucketing to deal with the varying sequences length problem and saved lots of computation time. I wonder if there's any way to make your class work as well as using bucketing, instead of padding. Thanks.

**Comment by th4t-gi** [comment]
@LeZhengThu
I was getting the same error as @ZmeiGorynych with the varying sequences. Is there any way to  use the AttentionDecoder class without bucketing/padding?
